/**
 * The icons this app can render — and deliberately nothing else.
 *
 * WHY THIS FILE EXISTS. `@lucide/angular` also exports an `icons` barrel
 * holding every icon it ships. Importing that barrel is what the three icon
 * components used to do, and because `ico` looks its entry up with a
 * runtime-computed key (\`Lucide\${name}\`) no bundler could narrow it: every
 * icon Lucide had ever published landed in `main.js`. On 2026-09-03 an
 * ordinary minor bump (1.18.0 -> 1.37.0) took the initial bundle from 1.68 MB
 * to 6.34 MB raw and broke the production build's 2.5 MB budget. Nothing in
 * the app had changed. That is the shape of the problem: the cost grew with
 * UPSTREAM releases, so it would have kept growing for free.
 *
 * Named imports are tree-shakeable, so this map costs only what it lists.
 *
 * HOW TO ADD AN ICON. Add the import and the entry, both alphabetical. You do
 * not need to find every call site first: `IconKey` is `keyof typeof
 * iconSet`, so asking for a name that is not here is a COMPILE error at the
 * call site, not a blank space at runtime. The production build is in the gate
 * for exactly this.
 *
 * HOW THIS LIST WAS DERIVED. `node tools/collect-icon-usage.mjs` scans the
 * templates and TypeScript for the four ways a name reaches `<app-ico>`:
 * a static `name="X"`, a literal inside a `[name]` expression, an
 * `icon:`/`ico:` property in a data table, and an explicit `IconKey`
 * annotation. It is a starting point, not an oracle — the compiler is the
 * oracle. Re-run it when pruning, never trust it alone when removing.
 */

import {
    LucideActivity,
    LucideAlertTriangle,
    LucideAperture,
    LucideArrowRight,
    LucideArrowUpToLine,
    LucideBarChart2,
    LucideBell,
    LucideBot,
    LucideBox,
    LucideBraces,
    LucideCheck,
    LucideChevronDown,
    LucideChevronFirst,
    LucideChevronLast,
    LucideChevronLeft,
    LucideChevronRight,
    LucideChevronUp,
    LucideClock,
    LucideCompass,
    LucideCopy,
    LucideCrop,
    LucideDatabase,
    LucideDownload,
    LucideEdit,
    LucideEdit3,
    LucideExternalLink,
    LucideEye,
    LucideFileCheck,
    LucideFileImage,
    LucideFileUp,
    LucideFiles,
    LucideFilm,
    LucideFlame,
    LucideFolder,
    LucideFolderMinus,
    LucideFolderOpen,
    LucideFolderPlus,
    LucideGitBranch,
    LucideGrid3x3,
    LucideHardDrive,
    LucideHash,
    LucideHistory,
    LucideImage,
    LucideImageOff,
    LucideInfo,
    LucideLayers,
    LucideLayoutGrid,
    LucideList,
    LucideLoader,
    LucideLoader2,
    LucideLoaderCircle,
    LucideMaximize,
    LucideMemoryStick,
    LucideMinimize,
    LucideMinus,
    LucideMoon,
    LucideMoreHorizontal,
    LucidePalette,
    LucidePencil,
    LucidePieChart,
    LucidePin,
    LucidePipette,
    LucidePlay,
    LucidePlus,
    LucideRectangleHorizontal,
    LucideRectangleVertical,
    LucideRefreshCw,
    LucideRotateCcw,
    LucideRotateCw,
    LucideSave,
    LucideScanLine,
    LucideScanSearch,
    LucideScissors,
    LucideScrollText,
    LucideSearch,
    LucideServer,
    LucideSettings,
    LucideShare2,
    LucideShield,
    LucideSliders,
    LucideSmile,
    LucideSparkles,
    LucideSquare,
    LucideSun,
    LucideTags,
    LucideThermometer,
    LucideTrash2,
    LucideTrendingUp,
    LucideTriangleAlert,
    LucideType,
    LucideUpload,
    LucideWand,
    LucideWand2,
    LucideWandSparkles,
    LucideWifiOff,
    LucideWrapText,
    LucideX,
    LucideZap,
    LucideZoomIn,
    LucideZoomOut,
} from '@lucide/angular';

/**
 * Name -> icon component. `ico` reads the component's static `icon` data.
 * `as const` is load-bearing: it is what makes `IconKey` the exact union of
 * these 100 names instead of `string`.
 */
export const iconSet = {
    Activity: LucideActivity,
    AlertTriangle: LucideAlertTriangle,
    Aperture: LucideAperture,
    ArrowRight: LucideArrowRight,
    ArrowUpToLine: LucideArrowUpToLine,
    BarChart2: LucideBarChart2,
    Bell: LucideBell,
    Bot: LucideBot,
    Box: LucideBox,
    Braces: LucideBraces,
    Check: LucideCheck,
    ChevronDown: LucideChevronDown,
    ChevronFirst: LucideChevronFirst,
    ChevronLast: LucideChevronLast,
    ChevronLeft: LucideChevronLeft,
    ChevronRight: LucideChevronRight,
    ChevronUp: LucideChevronUp,
    Clock: LucideClock,
    Compass: LucideCompass,
    Copy: LucideCopy,
    Crop: LucideCrop,
    Database: LucideDatabase,
    Download: LucideDownload,
    Edit: LucideEdit,
    Edit3: LucideEdit3,
    ExternalLink: LucideExternalLink,
    Eye: LucideEye,
    FileCheck: LucideFileCheck,
    FileImage: LucideFileImage,
    FileUp: LucideFileUp,
    Files: LucideFiles,
    Film: LucideFilm,
    Flame: LucideFlame,
    Folder: LucideFolder,
    FolderMinus: LucideFolderMinus,
    FolderOpen: LucideFolderOpen,
    FolderPlus: LucideFolderPlus,
    GitBranch: LucideGitBranch,
    Grid3x3: LucideGrid3x3,
    HardDrive: LucideHardDrive,
    Hash: LucideHash,
    History: LucideHistory,
    Image: LucideImage,
    ImageOff: LucideImageOff,
    Info: LucideInfo,
    Layers: LucideLayers,
    LayoutGrid: LucideLayoutGrid,
    List: LucideList,
    Loader: LucideLoader,
    Loader2: LucideLoader2,
    LoaderCircle: LucideLoaderCircle,
    Maximize: LucideMaximize,
    MemoryStick: LucideMemoryStick,
    Minimize: LucideMinimize,
    Minus: LucideMinus,
    Moon: LucideMoon,
    MoreHorizontal: LucideMoreHorizontal,
    Palette: LucidePalette,
    Pencil: LucidePencil,
    PieChart: LucidePieChart,
    Pin: LucidePin,
    Pipette: LucidePipette,
    Play: LucidePlay,
    Plus: LucidePlus,
    RectangleHorizontal: LucideRectangleHorizontal,
    RectangleVertical: LucideRectangleVertical,
    RefreshCw: LucideRefreshCw,
    RotateCcw: LucideRotateCcw,
    RotateCw: LucideRotateCw,
    Save: LucideSave,
    ScanLine: LucideScanLine,
    ScanSearch: LucideScanSearch,
    Scissors: LucideScissors,
    ScrollText: LucideScrollText,
    Search: LucideSearch,
    Server: LucideServer,
    Settings: LucideSettings,
    Share2: LucideShare2,
    Shield: LucideShield,
    Sliders: LucideSliders,
    Smile: LucideSmile,
    Sparkles: LucideSparkles,
    Square: LucideSquare,
    Sun: LucideSun,
    Tags: LucideTags,
    Thermometer: LucideThermometer,
    Trash2: LucideTrash2,
    TrendingUp: LucideTrendingUp,
    TriangleAlert: LucideTriangleAlert,
    Type: LucideType,
    Upload: LucideUpload,
    Wand: LucideWand,
    Wand2: LucideWand2,
    WandSparkles: LucideWandSparkles,
    WifiOff: LucideWifiOff,
    WrapText: LucideWrapText,
    X: LucideX,
    Zap: LucideZap,
    ZoomIn: LucideZoomIn,
    ZoomOut: LucideZoomOut,
} as const;

/**
 * Every name `<app-ico>` accepts. Widening this back to `string` would turn
 * every typo into a runtime crash, and re-introducing the barrel would turn it
 * into 1600 names and four megabytes.
 */
export type IconKey = keyof typeof iconSet;
